package com.reactiveworks.productwebservice.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-29T18:10:38.794-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ProductWebServiceService", 
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap-webservice/soapn-exercise/productserver/WebContent/wsdl/productwebservice.wsdl",
                  targetNamespace = "http://webservice.productwebservice.reactiveworks.com/") 
public class ProductWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.productwebservice.reactiveworks.com/", "ProductWebServiceService");
    public final static QName ProductWebServicePort = new QName("http://webservice.productwebservice.reactiveworks.com/", "ProductWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap-webservice/soapn-exercise/productserver/WebContent/wsdl/productwebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap-webservice/soapn-exercise/productserver/WebContent/wsdl/productwebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServicePort")
    public ProductWebService getProductWebServicePort() {
        return super.getPort(ProductWebServicePort, ProductWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServicePort")
    public ProductWebService getProductWebServicePort(WebServiceFeature... features) {
        return super.getPort(ProductWebServicePort, ProductWebService.class, features);
    }

}
