
package com.reactiveworks.productwebservice.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-29T18:10:38.741-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "ProductNotAvailableException", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
public class ProductNotAvailableException_Exception extends Exception {
    
    private com.reactiveworks.productwebservice.webservice.ProductNotAvailableException productNotAvailableException;

    public ProductNotAvailableException_Exception() {
        super();
    }
    
    public ProductNotAvailableException_Exception(String message) {
        super(message);
    }
    public static String response(String message, Throwable cause) {
		return "developer message: "+cause.getCause().getMessage()+"\\n user message: "+message;
	}
	
    
    public ProductNotAvailableException_Exception(String message, Throwable cause) {
        super(response(message,cause), cause);
    }

    public ProductNotAvailableException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductNotAvailableException productNotAvailableException) {
        super(message);
        this.productNotAvailableException = productNotAvailableException;
    }

    public ProductNotAvailableException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductNotAvailableException productNotAvailableException, Throwable cause) {
        super(message, cause);
        this.productNotAvailableException = productNotAvailableException;
    }

    public com.reactiveworks.productwebservice.webservice.ProductNotAvailableException getFaultInfo() {
        return this.productNotAvailableException;
    }
}
