package com.reactiveworks.productwebservice.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-29T18:10:38.788-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", name = "ProductWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductWebService {

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addProductsResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", partName = "parameters")
    public java.lang.String addProducts(
        @WebParam(partName = "products", name = "addProducts", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
        Products products
    ) throws ProductWebServiceFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.GetProductsResponse")
    @WebResult(name = "product", targetNamespace = "")
    public java.util.List<com.reactiveworks.productwebservice.webservice.Product> getProducts(
        @WebParam(name = "productId", targetNamespace = "")
        java.lang.String productId
    ) throws ProductWebServiceFailureException_Exception, ProductNotAvailableException_Exception;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteProductResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", partName = "parameters")
    public java.lang.String deleteProduct(
        @WebParam(partName = "parameters", name = "deleteProduct", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
        DeleteProduct parameters
    ) throws ProductWebServiceFailureException_Exception, ProductNotAvailableException_Exception,ProductIDMissingException_Exception;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateProductResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", partName = "parameters")
    public java.lang.String updateProduct(
        @WebParam(partName = "parameters", name = "updateProduct", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
        UpdateProduct parameters
    ) throws ProductWebServiceFailureException_Exception, ProductNotAvailableException_Exception,ProductIDMissingException_Exception;
}
