
package com.reactiveworks.productwebservice.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-29T18:10:38.752-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "ProductIDMissingException", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
public class ProductIDMissingException_Exception extends Exception {
    
    private com.reactiveworks.productwebservice.webservice.ProductIDMissingException productIDMissingException;

    public ProductIDMissingException_Exception() {
        super();
    }
    
    public ProductIDMissingException_Exception(String message) {
        super(message);
    }
    public static String response(String message, Throwable cause) {
		return "developer message: "+cause.getCause().getMessage()+" user message: "+message;
	}
	
    
    public ProductIDMissingException_Exception(String message, Throwable cause) {
        super(response(message,cause), cause);
    }

    public ProductIDMissingException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductIDMissingException productIDMissingException) {
        super(message);
        this.productIDMissingException = productIDMissingException;
    }

    public ProductIDMissingException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductIDMissingException productIDMissingException, Throwable cause) {
        super(message, cause);
        this.productIDMissingException = productIDMissingException;
    }

    public com.reactiveworks.productwebservice.webservice.ProductIDMissingException getFaultInfo() {
        return this.productIDMissingException;
    }
}
