
package com.reactiveworks.productwebservice.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-29T18:10:38.694-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "ProductWebServiceFailureException", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
public class ProductWebServiceFailureException_Exception extends Exception {
    
    private com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException;

    public ProductWebServiceFailureException_Exception() {
        super();
    }
    
    public ProductWebServiceFailureException_Exception(String message) {
        super(message);
    }
    public static String response(String message, Throwable cause) {
		return "developer message: "+cause.getCause().getMessage()+" user message: "+message;
	}
	
    public ProductWebServiceFailureException_Exception(String message, Throwable cause) {
        super(response(message,cause), cause);
    }

    public ProductWebServiceFailureException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException) {
        super(message);
        this.productWebServiceFailureException = productWebServiceFailureException;
    }

    public ProductWebServiceFailureException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException, Throwable cause) {
        super(message, cause);
        this.productWebServiceFailureException = productWebServiceFailureException;
    }

    public com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException getFaultInfo() {
        return this.productWebServiceFailureException;
    }
}
