
package com.reactiveworks.productwebservice.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-27T10:02:00.703-07:00
 * Generated source version: 3.2.1
 * 
 */
public final class ProductWebService_ProductWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.productwebservice.reactiveworks.com/", "ProductWebServiceService");

    private ProductWebService_ProductWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductWebServiceService ss = new ProductWebServiceService(wsdlURL, SERVICE_NAME);
        ProductWebService port = ss.getProductWebServicePort();  
        
        {
        System.out.println("Invoking addProducts...");
        java.util.List<com.reactiveworks.productwebservice.webservice.Product> _addProducts_product = new java.util.ArrayList<com.reactiveworks.productwebservice.webservice.Product>();
        com.reactiveworks.productwebservice.webservice.Product _addProducts_productVal1 = new com.reactiveworks.productwebservice.webservice.Product();
        _addProducts_productVal1.setProductId("ProductId-342121481");
        _addProducts_productVal1.setProductName("ProductName-572572460");
        _addProducts_productVal1.setProductCategory("ProductCategory-1080868504");
        _addProducts_productVal1.setPrice(Integer.valueOf(50019114));
        java.util.List<java.lang.String> _addProducts_productVal1AvailableCities = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addProducts_productVal1AvailableCitiesVal1 = "_addProducts_productVal1AvailableCitiesVal-1323866536";
        _addProducts_productVal1AvailableCities.add(_addProducts_productVal1AvailableCitiesVal1);
        _addProducts_productVal1.getAvailableCities().addAll(_addProducts_productVal1AvailableCities);
        _addProducts_product.add(_addProducts_productVal1);
        try {
            port.addProducts(_addProducts_product);

        } catch (ProductWebServiceFailureException_Exception e) { 
            System.out.println("Expected exception: ProductWebServiceFailureException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getProducts...");
        java.lang.String _getProducts_productId = "_getProducts_productId1048366187";
        try {
            java.util.List<com.reactiveworks.productwebservice.webservice.Product> _getProducts__return = port.getProducts(_getProducts_productId);
            System.out.println("getProducts.result=" + _getProducts__return);

        } catch (ProductWebServiceFailureException_Exception e) { 
            System.out.println("Expected exception: ProductWebServiceFailureException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteProduct...");
        java.lang.String _deleteProduct_productId = "_deleteProduct_productId1738097573";
        try {
            port.deleteProduct(_deleteProduct_productId);

        } catch (ProductWebServiceFailureException_Exception e) { 
            System.out.println("Expected exception: ProductWebServiceFailureException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
