package com.reactiveworks.productwebservice.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-27T10:02:00.770-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", name = "ProductWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductWebService {

    @WebMethod
    @RequestWrapper(localName = "addProducts", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.AddProducts")
    @ResponseWrapper(localName = "addProductsResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.AddProductsResponse")
    public void addProducts(
        @WebParam(name = "product", targetNamespace = "")
        java.util.List<com.reactiveworks.productwebservice.webservice.Product> product
    ) throws ProductWebServiceFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.GetProductsResponse")
    @WebResult(name = "user", targetNamespace = "")
    public java.util.List<com.reactiveworks.productwebservice.webservice.Product> getProducts(
        @WebParam(name = "productId", targetNamespace = "")
        java.lang.String productId
    ) throws ProductWebServiceFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/", className = "com.reactiveworks.productwebservice.webservice.DeleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "productId", targetNamespace = "")
        java.lang.String productId
    ) throws ProductWebServiceFailureException_Exception;
}
