
package com.reactiveworks.productwebservice.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-27T10:02:00.753-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "ProductWebServiceFailureException", targetNamespace = "http://webservice.productwebservice.reactiveworks.com/")
public class ProductWebServiceFailureException_Exception extends Exception {
    
    private com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException;

    public ProductWebServiceFailureException_Exception() {
        super();
    }
    
    public ProductWebServiceFailureException_Exception(String message) {
        super(message);
    }
    
    public ProductWebServiceFailureException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ProductWebServiceFailureException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException) {
        super(message);
        this.productWebServiceFailureException = productWebServiceFailureException;
    }

    public ProductWebServiceFailureException_Exception(String message, com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException productWebServiceFailureException, Throwable cause) {
        super(message, cause);
        this.productWebServiceFailureException = productWebServiceFailureException;
    }

    public com.reactiveworks.productwebservice.webservice.ProductWebServiceFailureException getFaultInfo() {
        return this.productWebServiceFailureException;
    }
}
